# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181018_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='NO IMAGE', upload_to='profpics/'),
        ),
    ]
