# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:16
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181018_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(default='Noisy Neigbhors'),
        ),
    ]
