# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181018_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='photo',
            field=models.ImageField(default='NO IMAGE', upload_to='profpics/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='neighbor_hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Neighborhood'),
        ),
    ]
