# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181020_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='neighbor_hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='app.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='app.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.Neighborhood'),
        ),
    ]
